#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <flipper_ml_icons.h>

int32_t flipper_ml_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm flipper_ml!");

    return 0;
}
